from .orders_data_serializer import OrdersDataSerializer
from .customers_data_serializer import CustomerDataSerializer
from .sensors_data_serializer import SensorDataSerializer
from .origin_data_serializer import OriginDataSerializer
from .rider_history_data_serializer import RiderHistoryDataSerializer