# Generated by Django 5.1.7 on 2025-03-30 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('wake_source', models.CharField(blank=True, max_length=50, null=True)),
                ('box_status', models.CharField(blank=True, max_length=50, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
