# Generated by Django 5.1.7 on 2025-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('latlng', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
