# Generated by Django 5.1.7 on 2025-03-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0004_customersdata_ordersdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersdata',
            old_name='latlng',
            new_name='coodinate',
        ),
    ]
