# Generated by Django 5.1.7 on 2025-03-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0005_rename_latlng_customersdata_coodinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersdata',
            name='phone_number',
        ),
    ]
