# Generated by Django 5.1.7 on 2025-03-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0006_remove_customersdata_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersdata',
            old_name='coodinate',
            new_name='coordinate',
        ),
    ]
