# Generated by Django 5.1.7 on 2025-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0007_rename_coodinate_customersdata_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latlng', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
