# Generated by Django 5.1.7 on 2025-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0008_origindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=100, unique=True)),
                ('total_distance', models.FloatField(default=0.0)),
            ],
        ),
    ]
