# Generated by Django 5.1.7 on 2025-03-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0009_riderhistorydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlanCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('rider_names_hash', models.CharField(max_length=256)),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
